#!/usr/bin/env node

var fs = require('fs');
var path = require('path');
var pkg = require('../package.json');
var bower = require('../bower.json');

// Update bower.json
Object.keys(bower).forEach((key) => {
    bower[key] = pkg[key] || bower[key];
});
bower.authors = pkg.contributors.map(author => {
    return author.name + " <" + author.email + ">";
});

fs.writeFileSync(path.join(__dirname, '../bower.json'), JSON.stringify(bower, null, 2), 'utf8');
